/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenlab2p2_salvadormacias;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Apple
 */
public class simuladorFootball extends javax.swing.JFrame {

    /**
     * Creates new form simuladorFootball
     */
    public simuladorFootball() {
        initComponents();
        textArea_Acciones.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogNuevoJuego = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_Acciones = new javax.swing.JTextArea();
        lbl_marcador = new javax.swing.JLabel();
        lbl_cuarto = new javax.swing.JLabel();
        lbl_posesion = new javax.swing.JLabel();
        lbl_tiempo = new javax.swing.JLabel();
        label_posicionCampo = new javax.swing.JLabel();
        lbl_posesion1 = new javax.swing.JLabel();
        dialogEquipos = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_equipo = new javax.swing.JComboBox<>();
        cb_rival = new javax.swing.JComboBox<>();
        btn_comenzarJuego = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_nuevoJuego = new javax.swing.JButton();
        bbnMostarResultado = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenlab2p2_salvadormacias/campo.jpg"))); // NOI18N

        textArea_Acciones.setColumns(20);
        textArea_Acciones.setRows(5);
        jScrollPane1.setViewportView(textArea_Acciones);

        lbl_marcador.setText("jLabel5");

        lbl_cuarto.setText("jLabel5");

        lbl_posesion.setText("jLabel5");

        lbl_tiempo.setText("jLabel5");

        label_posicionCampo.setText("jLabel5");

        lbl_posesion1.setText("posesion:");

        javax.swing.GroupLayout dialogNuevoJuegoLayout = new javax.swing.GroupLayout(dialogNuevoJuego.getContentPane());
        dialogNuevoJuego.getContentPane().setLayout(dialogNuevoJuegoLayout);
        dialogNuevoJuegoLayout.setHorizontalGroup(
            dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogNuevoJuegoLayout.createSequentialGroup()
                .addGroup(dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(dialogNuevoJuegoLayout.createSequentialGroup()
                .addGroup(dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(dialogNuevoJuegoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_marcador)
                        .addGap(248, 248, 248)
                        .addComponent(lbl_tiempo))
                    .addGroup(dialogNuevoJuegoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbl_posesion1)
                        .addGap(43, 43, 43)
                        .addComponent(lbl_posesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_posicionCampo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_cuarto)
                .addGap(109, 109, 109))
        );
        dialogNuevoJuegoLayout.setVerticalGroup(
            dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogNuevoJuegoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tiempo)
                    .addComponent(lbl_cuarto)
                    .addComponent(lbl_marcador))
                .addGap(21, 21, 21)
                .addGroup(dialogNuevoJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_posesion)
                    .addComponent(label_posicionCampo)
                    .addComponent(lbl_posesion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
        );

        jLabel3.setText("seleccione un equipo:");

        jLabel4.setText("vs");

        cb_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "eagles", "lions", "bobcats", "tiguers", "sharks" }));

        cb_rival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "eagles", "lions", "bobcats", "tiguers", "sharks" }));

        btn_comenzarJuego.setText("comenzar");
        btn_comenzarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comenzarJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogEquiposLayout = new javax.swing.GroupLayout(dialogEquipos.getContentPane());
        dialogEquipos.getContentPane().setLayout(dialogEquiposLayout);
        dialogEquiposLayout.setHorizontalGroup(
            dialogEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEquiposLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(dialogEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogEquiposLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogEquiposLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(cb_rival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
            .addGroup(dialogEquiposLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btn_comenzarJuego)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogEquiposLayout.setVerticalGroup(
            dialogEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogEquiposLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addGap(60, 60, 60)
                .addGroup(dialogEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_rival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btn_comenzarJuego)
                .addGap(79, 79, 79))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenlab2p2_salvadormacias/Apple-Arcade-hero_big.jpg"))); // NOI18N

        btn_nuevoJuego.setText("nuevo juego");
        btn_nuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoJuegoActionPerformed(evt);
            }
        });

        bbnMostarResultado.setText("Mostrar Resultado");
        bbnMostarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbnMostarResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btn_nuevoJuego)
                        .addGap(273, 273, 273)
                        .addComponent(bbnMostarResultado)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevoJuego)
                    .addComponent(bbnMostarResultado))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoJuegoActionPerformed
        //this.setVisible(false);
        dialogEquipos.setVisible(true);
        dialogEquipos.pack();

// TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoJuegoActionPerformed

    private void btn_comenzarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comenzarJuegoActionPerformed

        Thread tempJuego = new Thread(() -> {
            int segundos = 75;
            int yardasTotales = 100;
            int yardaActual = 25;
            int intentos = 4;
            int puntosEquipo = 0;
            int puntosRival = 0;
            int x = 1;

            boolean posesionJugador = true;

            Random rand = new Random();

            try {
                for (int i = 1; i <= segundos; i++) {
                    int cuarto = i /11;
                    System.out.println("Segundo: " + i);

                    Thread.sleep(1000);
                    // System.out.println(i);

                    dialogEquipos.setVisible(false);
                    dialogNuevoJuego.setVisible(true);
                    dialogNuevoJuego.pack();

                    lbl_marcador.setText(cb_equipo.getSelectedItem().toString() + " "+ puntosEquipo + " -  " + puntosRival + " "+ cb_rival.getSelectedItem().toString());
                    lbl_posesion.setText(posesionJugador ? cb_equipo.getSelectedItem().toString() : cb_rival.getSelectedItem().toString());
                    lbl_tiempo.setText("tiempo: " + i);
                    lbl_cuarto.setText("cuarto: " + cuarto );
                    label_posicionCampo.setText("Yarda actual: " + yardaActual);

                    int avance = rand.nextInt(11);
                    yardaActual += avance;
                    intentos--;

                    String equipoActual = posesionJugador ? cb_equipo.getSelectedItem().toString() : cb_rival.getSelectedItem().toString();
                    textArea_Acciones.append(i + " s - " + equipoActual + " corrió " + avance + " yardas\n");

                    if (yardaActual >= yardasTotales) {
                        textArea_Acciones.append("Touchdown de " + equipoActual + " +7 puntos\n");

                        if (posesionJugador) {
                            puntosEquipo += 7;
                        } else {
                            puntosRival += 7;
                        }

                        yardaActual = 25;
                        intentos = 4;
                        posesionJugador = !posesionJugador;
                        textArea_Acciones.append("cambio de posesion portouchdown\n\n");
                        continue;
                    }

                    if (intentos == 0) {
                        textArea_Acciones.append("cambio de posesion por falta de intentos\n\n");

                        yardaActual = 25;
                        intentos = 4;
                        posesionJugador = !posesionJugador;

                        if (yardaActual >= yardasTotales) {
                            textArea_Acciones.append("Touchdown de " + equipoActual + "\n");
                        }

                    }

                    //   textArea_Acciones.append(i + " s -" + cb_equipo.getSelectedItem().toString()
                    //           + " corrieron " + i + " yardas " + "\n");
                    if (i == 0) {

                    }

                    x = x++;
                    if (i == 75) {
                        resultados.add(1);
                        JOptionPane.showMessageDialog(this, lbl_marcador.getText());

                        JFileChooser filechooser = new JFileChooser();
                        int estado = filechooser.showSaveDialog(this);
                        if (estado == JFileChooser.APPROVE_OPTION) {
                            seleccionado = filechooser.getSelectedFile();
                            try {

                                BufferedWriter br = new BufferedWriter(new FileWriter(seleccionado, false));
                                String nuevaInfo = lbl_marcador.getText();
                                br.write("\n" + nuevaInfo);
                                br.close();
                                JOptionPane.showMessageDialog(this, "se  guardo el resultado");
                                textArea_Acciones.setText(" ");
                                filechooser.setVisible(false);
                                // dialogNuevoJuego.setVisible(false);

                            } catch (IOException ex) {

                                Logger.getLogger(simuladorFootball.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }

                    }

                }

            } catch (InterruptedException e) {

            }
            // dialogNuevoJuego.setVisible(false);

        }
        );

        tempJuego.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_comenzarJuegoActionPerformed

    private void bbnMostarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbnMostarResultadoActionPerformed

        if (resultados.size() == 0) {
            JOptionPane.showMessageDialog(this, "no hay resultados guardados");
        } else {
            JOptionPane.showMessageDialog(this, lbl_marcador.getText());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bbnMostarResultadoActionPerformed

    private void leerResultado(File file) {
        try {

            BufferedReader br = new BufferedReader(new FileReader(seleccionado));
            String linea = br.readLine();

            while (linea != null) {

                // jTextArea1.append(linea + "\n");
                JOptionPane.showMessageDialog(this, linea);

                linea = br.readLine();

            }

        } catch (FileNotFoundException ex) {
        } catch (IOException ex) {
            Logger.getLogger(simuladorFootball.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedAudioFileException, IOException, LineUnavailableException, InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simuladorFootball.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simuladorFootball.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simuladorFootball.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simuladorFootball.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simuladorFootball().setVisible(true);
                try {
                    File audioFile = new File("/Users/Apple/Downloads/NBC-Sunday-Night-Football.wav");
                    AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
                    Clip clip = AudioSystem.getClip();
                    clip.open(audioStream);

                    clip.loop(Clip.LOOP_CONTINUOUSLY);
                    clip.start();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        });
    }

    public static File seleccionado;
    ArrayList resultados = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbnMostarResultado;
    private javax.swing.JButton btn_comenzarJuego;
    private javax.swing.JButton btn_nuevoJuego;
    private javax.swing.JComboBox<String> cb_equipo;
    private javax.swing.JComboBox<String> cb_rival;
    private javax.swing.JDialog dialogEquipos;
    private javax.swing.JDialog dialogNuevoJuego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_posicionCampo;
    private javax.swing.JLabel lbl_cuarto;
    private javax.swing.JLabel lbl_marcador;
    private javax.swing.JLabel lbl_posesion;
    private javax.swing.JLabel lbl_posesion1;
    private javax.swing.JLabel lbl_tiempo;
    private javax.swing.JTextArea textArea_Acciones;
    // End of variables declaration//GEN-END:variables
}
